### ISSUE TITLE
TODO: write about "module not found" error for ignored node dependencies.

### ISSUE THREAD

**Issue by StevenMasini** [raquo/facebook-flow-examples#2]
Hi raquo,

Can you write about "module not found", I am new with facebook flow, and I am sicking some help to solve this issue.

**Comment by raquo** [comment]
Hey, sorry – it's been so long, I don't actually remember what I meant by that `@TODO`. And even if I remembered, Flow has seen 30 releases since I last used it, so all bets are off on what they've changed in all that time. You're better off asking on Stack Overflow if you're facing a specific error. Good luck!
